"""empty message

Revision ID: 0b2607395f8c
Revises: 
Create Date: 2018-07-26 19:41:00.048958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b2607395f8c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authors',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('author', sa.VARCHAR(length=255), nullable=True),
    sa.Column('date_of_birth', sa.VARCHAR(length=255), nullable=True),
    sa.Column('date_of_death', sa.VARCHAR(length=255), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('educated_at', sa.VARCHAR(length=255), nullable=True),
    sa.Column('gender', sa.VARCHAR(length=10), nullable=True),
    sa.Column('occupation', sa.VARCHAR(length=255), nullable=True),
    sa.Column('place_of_birth', sa.VARCHAR(length=255), nullable=True),
    sa.Column('place_of_burial', sa.VARCHAR(length=255), nullable=True),
    sa.Column('place_of_death', sa.VARCHAR(length=255), nullable=True),
    sa.Column('year_of_birth', sa.INTEGER(), nullable=True),
    sa.Column('year_of_death', sa.INTEGER(), nullable=True),
    sa.Column('month_of_birth', sa.INTEGER(), nullable=True),
    sa.Column('month_of_death', sa.INTEGER(), nullable=True),
    sa.Column('day_of_birth', sa.INTEGER(), nullable=True),
    sa.Column('day_of_death', sa.INTEGER(), nullable=True),
    sa.Column('image_location', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='poetry'
    )
    op.create_index(op.f('ix_poetry_authors_author'), 'authors', ['author'], unique=True, schema='poetry')
    op.create_table('poems',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('author', sa.VARCHAR(length=255), nullable=True),
    sa.Column('linecount', sa.INTEGER(), nullable=True),
    sa.Column('lines', sa.TEXT(), nullable=True),
    sa.Column('title', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lines'),
    sa.UniqueConstraint('title'),
    schema='poetry'
    )
    op.drop_index('ix_poetry.authors_df_id', table_name='poetry.authors_df')
    op.drop_table('poetry.authors_df')
    op.drop_index('ix_poetry.poems_df_id', table_name='poetry.poems_df')
    op.drop_table('poetry.poems_df')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('poetry.poems_df',
    sa.Column('id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('author', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('linecount', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('lines', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.create_index('ix_poetry.poems_df_id', 'poetry.poems_df', ['id'], unique=False)
    op.create_table('poetry.authors_df',
    sa.Column('id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('authors', sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.create_index('ix_poetry.authors_df_id', 'poetry.authors_df', ['id'], unique=False)
    op.drop_table('poems', schema='poetry')
    op.drop_index(op.f('ix_poetry_authors_author'), table_name='authors', schema='poetry')
    op.drop_table('authors', schema='poetry')
    # ### end Alembic commands ###
