"""empty message

Revision ID: 7b40d656de5d
Revises: 
Create Date: 2018-07-08 07:32:32.432874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b40d656de5d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_author_author', table_name='author')
    op.drop_table('author')
    op.alter_column('authors', 'author',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_index(op.f('ix_authors_author'), 'authors', ['author'], unique=True)
    op.create_unique_constraint(None, 'poems', ['title'])
    op.create_unique_constraint(None, 'poems', ['lines'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'poems', type_='unique')
    op.drop_constraint(None, 'poems', type_='unique')
    op.drop_index(op.f('ix_authors_author'), table_name='authors')
    op.alter_column('authors', 'author',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.create_table('author',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('author', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='author_pkey')
    )
    op.create_index('ix_author_author', 'author', ['author'], unique=True)
    # ### end Alembic commands ###
